### ISSUE TITLE
outdated docs: build/host environment activation order reversed

### ISSUE THREAD

**Issue by mbargull** [conda/conda-docs#576]
As of https://github.com/conda/conda-build/pull/2686, https://github.com/conda/conda-build/releases/tag/3.6.0, the activation order of `host` and `build` is reversed. The docs still reflect the old behavior.

**Comment by mbargull** [comment]
@msarahan, I have question regarding that activation order:
Imagine we have a `build_tool_depending_on_python` package (e.g., some compiler) with a (potentially transitive) dependency on `python`. Now I want to build a Python package with a C extension, i.e., I have
```yaml
package:
  name: build_tool_depending_on_python
  version: 1.0
requirements:
  run:
    - python
```
and
```yaml
package:
  name: some-package
  version: 0.1.0
build:
  script: python setup.py install
requirements:
  build:
    - build_tool_depending_on_python
  host:
    - python
  run:
    - python
```
. With `build` being activated after `host` in `conda-build >=3.6.0`, `python` will be the one from `build`, hence the package wouldn't build successfully since we didn't touch `host`'s `python`.
What should I do in such a case?
